spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:agencia}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Postgres2019!}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
