spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
cors:
  origins: ${CORS_ORIGINS:*}
